/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package pvoe.tarea2;

import javax.swing.JOptionPane; //accion de boton
/**
 *
 * @author rober
 */
public class Tarea2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tarea2.class.getName());

    
    
    // Variables para almacenar los datos del alumno
    private String generoSeleccionado= "";
    private String divisionSeleccionada= "";
    private java.util.List<String> actividadesSeleccionadas= new java.util.ArrayList<>();
    

    
    
    
    /**
     * Creates new form Tarea2
     */
    public Tarea2() {
        initComponents();
        asignarBotonesRadiales();
    }

    public void asignarBotonesRadiales()
    {
        // Botones de genero
        buttonGroup1.add(botonMasculino);
        buttonGroup1.add(botonFemenino);
        buttonGroup1.add(botonNoBinario);
        
        
        // Botones de division
        buttonGroup2.add(botonCBI);
        buttonGroup2.add(botonCSH);
        buttonGroup2.add(botonCyAD);

    }
    
    
    private void limpiarCampos() 
    {
        campoTextoMatricula.setText("");
        campoTextoNombre.setText("");
        campoTextoPrimerApellido.setText("");
        campoTextoSegundoApellido.setText("");
        campoTextoEdad.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        checkboxEncuestas.setSelected(false);
        checkboxProcesoInscripcion.setSelected(false);
        checkboxPERAJ.setSelected(false);
        generoSeleccionado = "";
        divisionSeleccionada = "";
        actividadesSeleccionadas.clear();
    }

    
    
    private boolean validarCampos() 
    {
        if (campoTextoNombre.getText().trim().isEmpty() || !campoTextoNombre.getText().trim().matches("[a-zA-Z ]+")) 
        {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio y solo puede tener letras.");
            return false;
        }
        if (campoTextoPrimerApellido.getText().trim().isEmpty() || !campoTextoPrimerApellido.getText().trim().matches("[a-zA-Z ]+")) 
        {
            JOptionPane.showMessageDialog(this, "El primer apellido es obligatorio y solo puede tener letras.");
            return false;
        }
        if (campoTextoSegundoApellido.getText().trim().isEmpty() || !campoTextoSegundoApellido.getText().trim().matches("[a-zA-Z ]+")) 
        {
            JOptionPane.showMessageDialog(this, "El segundo apellido es obligatorio y solo puede tener letras.");
            return false;
        }
        if (campoTextoMatricula.getText().trim().isEmpty() || !campoTextoMatricula.getText().trim().matches("\\d+")) 
        {
            JOptionPane.showMessageDialog(this, "La matricula es obligatoria y solo puede tener numeros.");
            return false;
        }
        if (campoTextoEdad.getText().trim().isEmpty() || !campoTextoEdad.getText().trim().matches("\\d+") || Integer.parseInt(campoTextoEdad.getText().trim()) <= 0) 
        {
            JOptionPane.showMessageDialog(this, "La edad debe ser un numero y mayor que 0");
            return false;
        }
        
        

        if (generoSeleccionado.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un genero.");
            return false;
        }
        if (divisionSeleccionada.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una division.");
            return false;
        }

        return true; // todo ok
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        labelNombre = new javax.swing.JLabel();
        labelPrimerApellido = new javax.swing.JLabel();
        labelSegundoApellido = new javax.swing.JLabel();
        campoTextoNombre = new javax.swing.JTextField();
        campoTextoPrimerApellido = new javax.swing.JTextField();
        campoTextoSegundoApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        etiquetaMatricula = new javax.swing.JLabel();
        campoTextoMatricula = new javax.swing.JTextField();
        etiquetaEdad = new javax.swing.JLabel();
        campoTextoEdad = new javax.swing.JTextField();
        etiquetaGenero = new javax.swing.JLabel();
        botonFemenino = new javax.swing.JRadioButton();
        botonNoBinario = new javax.swing.JRadioButton();
        botonMasculino = new javax.swing.JRadioButton();
        etiquetaDivision = new javax.swing.JLabel();
        botonCBI = new javax.swing.JRadioButton();
        botonCSH = new javax.swing.JRadioButton();
        botonCyAD = new javax.swing.JRadioButton();
        etiquetaActividadesInteres = new javax.swing.JLabel();
        checkboxEncuestas = new javax.swing.JCheckBox();
        checkboxProcesoInscripcion = new javax.swing.JCheckBox();
        checkboxPERAJ = new javax.swing.JCheckBox();
        botonRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Actividades");

        labelNombre.setText("Nombre");

        labelPrimerApellido.setText("Primer Apellido");

        labelSegundoApellido.setText("Segundo Apellido");

        campoTextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Sistema de Registro de Actividades de cada Estudiante");

        etiquetaMatricula.setText("Matricula");

        etiquetaEdad.setText("Edad");

        campoTextoEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoEdadActionPerformed(evt);
            }
        });

        etiquetaGenero.setText("Genero");

        botonFemenino.setText("Femenino");
        botonFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFemeninoActionPerformed(evt);
            }
        });

        botonNoBinario.setText("No binario");
        botonNoBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoBinarioActionPerformed(evt);
            }
        });

        botonMasculino.setText("Masculino");
        botonMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasculinoActionPerformed(evt);
            }
        });

        etiquetaDivision.setText("Division");

        botonCBI.setText("CBI");
        botonCBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCBIActionPerformed(evt);
            }
        });

        botonCSH.setText("CSH");
        botonCSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCSHActionPerformed(evt);
            }
        });

        botonCyAD.setText("CyAD");
        botonCyAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCyADActionPerformed(evt);
            }
        });

        etiquetaActividadesInteres.setText("Actividades que te interesan");

        checkboxEncuestas.setText("Encuestas");
        checkboxEncuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxEncuestasActionPerformed(evt);
            }
        });

        checkboxProcesoInscripcion.setText("Proceso de Inscripcion");
        checkboxProcesoInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxProcesoInscripcionActionPerformed(evt);
            }
        });

        checkboxPERAJ.setText("PERAJ");
        checkboxPERAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxPERAJActionPerformed(evt);
            }
        });

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTextoSegundoApellido)
                            .addComponent(campoTextoNombre)
                            .addComponent(campoTextoPrimerApellido)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonCBI)
                                .addGap(18, 18, 18)
                                .addComponent(botonCSH)
                                .addGap(18, 18, 18)
                                .addComponent(botonCyAD))
                            .addComponent(labelSegundoApellido)
                            .addComponent(etiquetaMatricula)
                            .addComponent(labelPrimerApellido)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTextoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaEdad)
                            .addComponent(campoTextoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaGenero))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaDivision)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonRegistrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonMasculino)
                                .addGap(18, 18, 18)
                                .addComponent(botonFemenino)
                                .addGap(18, 18, 18)
                                .addComponent(botonNoBinario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaActividadesInteres)
                                    .addComponent(checkboxEncuestas)
                                    .addComponent(checkboxProcesoInscripcion)
                                    .addComponent(checkboxPERAJ))))
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPrimerApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSegundoApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(etiquetaMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaEdad)
                .addGap(12, 12, 12)
                .addComponent(campoTextoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonMasculino)
                            .addComponent(botonFemenino)
                            .addComponent(botonNoBinario))
                        .addGap(42, 42, 42)
                        .addComponent(etiquetaDivision)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCBI)
                            .addComponent(botonCSH)
                            .addComponent(botonCyAD)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(etiquetaActividadesInteres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkboxEncuestas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkboxProcesoInscripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkboxPERAJ)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(botonRegistrar)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNombreActionPerformed

    private void campoTextoEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoEdadActionPerformed

    private void botonFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFemeninoActionPerformed
        generoSeleccionado= "Femenino";
    }//GEN-LAST:event_botonFemeninoActionPerformed

    private void checkboxProcesoInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxProcesoInscripcionActionPerformed
        if(checkboxProcesoInscripcion.isSelected())
        {
            actividadesSeleccionadas.add("Proceso de Inscripcion");
        }
        else 
        {
            actividadesSeleccionadas.remove("Proceso de Inscripcion");
        }
    }//GEN-LAST:event_checkboxProcesoInscripcionActionPerformed

    
    
    
    
    
    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        if (!validarCampos())
        {
            return; // si al validar los campos alguno da false, se termina y no se guarda
        }
        
        
        try
        {
            // Obtener lo de los campos de texto
            String nombre = campoTextoNombre.getText().trim(); // .trim para eliminar espacios en blanco
            String matricula= campoTextoMatricula.getText().trim(); 
            String primerApellido= campoTextoPrimerApellido.getText().trim();
            String segundoApellido= campoTextoSegundoApellido.getText().trim();
            String edad= campoTextoEdad.getText().trim();
            String genero= generoSeleccionado;
            String division= divisionSeleccionada;

            // Obtener lo de los botones radiales
            java.util.List<String> actividades_interes= new java.util.ArrayList<>(actividadesSeleccionadas); // arreglo para guardar en el.dat despues
            if(actividades_interes.isEmpty())
            {
                actividades_interes.add("NINGUNA"); 
            }            
            
            
            String linea_guardar_archivo= String.join(",",matricula,nombre,primerApellido,segundoApellido,edad,genero,division, String.join(",",actividades_interes));
                    
          
            try (java.io.FileWriter fw= new java.io.FileWriter("registros.dat", true)) 
            {
                fw.write(linea_guardar_archivo + System.lineSeparator());
            }
            JOptionPane.showMessageDialog(null, "Registro guardado correctamente.");
            
            limpiarCampos();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error al registrar" + e.getMessage());
        }
        
    }//GEN-LAST:event_botonRegistrarActionPerformed

    
    
    
    
    
    
    
    private void botonMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasculinoActionPerformed
        generoSeleccionado= "Masculino";
    }//GEN-LAST:event_botonMasculinoActionPerformed

    private void botonNoBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoBinarioActionPerformed
        generoSeleccionado= "No binario";
    }//GEN-LAST:event_botonNoBinarioActionPerformed

    private void botonCBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCBIActionPerformed
        divisionSeleccionada= "CBI";
    }//GEN-LAST:event_botonCBIActionPerformed

    private void botonCSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCSHActionPerformed
        divisionSeleccionada= "CSH";
    }//GEN-LAST:event_botonCSHActionPerformed

    private void botonCyADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCyADActionPerformed
        divisionSeleccionada= "CyAD";
    }//GEN-LAST:event_botonCyADActionPerformed

    private void checkboxEncuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxEncuestasActionPerformed
        if(checkboxEncuestas.isSelected())
        {
            actividadesSeleccionadas.add("Encuestas");
        }
        else 
        {
            actividadesSeleccionadas.remove("Encuestas");
        }
    }//GEN-LAST:event_checkboxEncuestasActionPerformed

    private void checkboxPERAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxPERAJActionPerformed
        if(checkboxPERAJ.isSelected())
        {
            actividadesSeleccionadas.add("PERAJ");
        }
        else 
        {
            actividadesSeleccionadas.remove("PERAJ");
        }
    }//GEN-LAST:event_checkboxPERAJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tarea2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonCBI;
    private javax.swing.JRadioButton botonCSH;
    private javax.swing.JRadioButton botonCyAD;
    private javax.swing.JRadioButton botonFemenino;
    private javax.swing.JRadioButton botonMasculino;
    private javax.swing.JRadioButton botonNoBinario;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextField campoTextoEdad;
    private javax.swing.JTextField campoTextoMatricula;
    private javax.swing.JTextField campoTextoNombre;
    private javax.swing.JTextField campoTextoPrimerApellido;
    private javax.swing.JTextField campoTextoSegundoApellido;
    private javax.swing.JCheckBox checkboxEncuestas;
    private javax.swing.JCheckBox checkboxPERAJ;
    private javax.swing.JCheckBox checkboxProcesoInscripcion;
    private javax.swing.JLabel etiquetaActividadesInteres;
    private javax.swing.JLabel etiquetaDivision;
    private javax.swing.JLabel etiquetaEdad;
    private javax.swing.JLabel etiquetaGenero;
    private javax.swing.JLabel etiquetaMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPrimerApellido;
    private javax.swing.JLabel labelSegundoApellido;
    // End of variables declaration//GEN-END:variables
}
