/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.practica.formas;

import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

import uam.pvoe.practica.modelo.ConversorTemperatura;

/**
 *
 * @author
 */
public class FrmConversiones extends javax.swing.JFrame {

    /**
     * Creates new form FrmConversiones
     */

    public FrmConversiones() {
        initComponents();
        asignarRangos();

        grupoTemperaturas.add(rbCentigrados);
        grupoTemperaturas.add(rbFahrenheit);
        grupoTemperaturas.add(rbKelvin);

        actualizarVisibilidadCampos();
        mostrarConversion();
    }

    private String obtenerTemperaturaOrigen() {
        if (rbCentigrados.isSelected()) {
            return "Centigrados";
        }
        if (rbFahrenheit.isSelected()) {
            return "Fahrenheit";
        }
        if (rbKelvin.isSelected()) {
            return "Kelvin";
        }
        return "";
    }

    private void actualizarVisibilidadCampos() {

        boolean mostrarCentigrados = !rbCentigrados.isSelected();
        txtCentigrados.setVisible(mostrarCentigrados);
        lblCentigrados.setVisible(mostrarCentigrados);


        boolean mostrarFahrenheit = !rbFahrenheit.isSelected();
        txtFahrenheit.setVisible(mostrarFahrenheit);
        lblFar.setVisible(mostrarFahrenheit);

        boolean mostrarKelvin = !rbKelvin.isSelected();
        txtKelvin.setVisible(mostrarKelvin);
        lblKelvin.setVisible(mostrarKelvin);
    }

    private void mostrarConversion() {
        double valor = Double.parseDouble(spnrTemperatura.getValue().toString());
        String origen = obtenerTemperaturaOrigen();
        double[] resultados = ConversorTemperatura.convertir(valor, origen);

        if (!rbCentigrados.isSelected()) {
            txtCentigrados.setText(String.format("%.2f", resultados[0]));
        }
        if (!rbFahrenheit.isSelected()) {
            txtFahrenheit.setText(String.format("%.2f", resultados[1]));
        }
        if (!rbKelvin.isSelected()) {
            txtKelvin.setText(String.format("%.2f", resultados[2]));
        }
    }

    private void asignarRangos() {
        SpinnerModel spnrModel = new SpinnerNumberModel(0, -100, 100, 1);
        spnrTemperatura.setModel(spnrModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTemperaturas = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        spnrTemperatura = new javax.swing.JSpinner();
        txtCentigrados = new javax.swing.JTextField();
        txtFahrenheit = new javax.swing.JTextField();
        txtKelvin = new javax.swing.JTextField();
        lblCentigrados = new javax.swing.JLabel();
        lblFar = new javax.swing.JLabel();
        lblKelvin = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        rbCentigrados = new javax.swing.JRadioButton();
        rbFahrenheit = new javax.swing.JRadioButton();
        rbKelvin = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversiones de Temperaturas");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblTitulo.setText("Sistema de Conversiones");

        spnrTemperatura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnrTemperaturaStateChanged(evt);
            }
        });

        txtCentigrados.setText("jTextField1");

        txtFahrenheit.setText("jTextField2");

        txtKelvin.setText("jTextField3");

        lblCentigrados.setText("Grados Centígrados");

        lblFar.setText("Grados  Fahrenheit");

        lblKelvin.setText("Grados Kelvin");

        lblOrigen.setText("Temperatura Origen");

        rbCentigrados.setSelected(true);
        rbCentigrados.setText("Grados Centígrados");
        rbCentigrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCentigradosActionPerformed(evt);
            }
        });

        rbFahrenheit.setText("Grados Fahrenheit");
        rbFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFahrenheitActionPerformed(evt);
            }
        });

        rbKelvin.setText("Grados Kelvin");
        rbKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKelvinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spnrTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrigen)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbCentigrados)
                                    .addComponent(rbKelvin, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbFahrenheit, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKelvin)
                            .addComponent(lblFar)
                            .addComponent(lblCentigrados)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCentigrados, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .addComponent(txtFahrenheit)
                                .addComponent(txtKelvin)))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitulo)
                .addGap(38, 38, 38)
                .addComponent(lblCentigrados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCentigrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrigen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnrTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblFar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelvin)
                    .addComponent(rbCentigrados))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKelvin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(rbFahrenheit)))
                .addGap(37, 37, 37)
                .addComponent(rbKelvin)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCentigradosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbCentigradosActionPerformed
        // TODO add your handling code here:
        actualizarVisibilidadCampos();
        mostrarConversion();
    }// GEN-LAST:event_rbCentigradosActionPerformed

    private void rbFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbFahrenheitActionPerformed
        // TODO add your handling code here:
        actualizarVisibilidadCampos();
        mostrarConversion();
    }// GEN-LAST:event_rbFahrenheitActionPerformed

    private void rbKelvinActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rbKelvinActionPerformed
        // TODO add your handling code here:
        actualizarVisibilidadCampos();
        mostrarConversion();
    }// GEN-LAST:event_rbKelvinActionPerformed

    private void spnrTemperaturaStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_spnrTemperaturaStateChanged
        // TODO add your handling code here:
        mostrarConversion();
    }// GEN-LAST:event_spnrTemperaturaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConversiones.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConversiones.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConversiones.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConversiones.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConversiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoTemperaturas;
    private javax.swing.JLabel lblCentigrados;
    private javax.swing.JLabel lblFar;
    private javax.swing.JLabel lblKelvin;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbCentigrados;
    private javax.swing.JRadioButton rbFahrenheit;
    private javax.swing.JRadioButton rbKelvin;
    private javax.swing.JSpinner spnrTemperatura;
    private javax.swing.JTextField txtCentigrados;
    private javax.swing.JTextField txtFahrenheit;
    private javax.swing.JTextField txtKelvin;
    // End of variables declaration//GEN-END:variables
}
