/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.pvoe.sw.buttons.formas;

import java.util.Enumeration;
import java.util.LinkedList;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import uam.pvoe.sw.buttons.modelo.RegistroSelecciones;

/**
 *
 * @author btosk
 */


public class FrmButtons extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmButtons.class.getName());

    /**
     * Creates new form FrmButtons
     */
    
    
    
    // Hacer una linkedlist para agrupar los checkboxes
    LinkedList <JCheckBox>listaChkBoxesLenguaje = new LinkedList();
    LinkedList <JCheckBox>listaChkBoxesIdioma = new LinkedList();
    
    
    
    public FrmButtons() {
        initComponents();
        asignarRadioButtons();
        agruparCheckBoxesLenguaje();
        agruparCheckBoxesIdioma();
        inicializarSelecciones();
    }

    public void asignarRadioButtons(){
    /*Creando el grupo de Genero*/
    buttonGroup1.add(rbFemenino);
    buttonGroup1.add(rbMasculino);
    /*Creando el grupo de Estado Civil*/
    buttonGroup2.add(rbCasado);
    buttonGroup2.add(rbDivorciado);
    buttonGroup2.add(rbSoltero);
    buttonGroup2.add(rbUnionLibre);
    /*Creando el grupo de Nacionalidad*/
    buttonGroup3.add(rbMexicano);
    buttonGroup3.add(rbExtranjero);
    }
    
    
    
    public void agruparCheckBoxesLenguaje(){
        listaChkBoxesLenguaje.add(cbCS);
        listaChkBoxesLenguaje.add(cbCPP);
        listaChkBoxesLenguaje.add(cbJava);
        listaChkBoxesLenguaje.add(cbPHP);
        listaChkBoxesLenguaje.add(cbOtroLenguaje);
    }
    
    public void agruparCheckBoxesIdioma(){
        listaChkBoxesIdioma.add(cbFrances);
        listaChkBoxesIdioma.add(cbIngles);
        listaChkBoxesIdioma.add(cbAleman);
        listaChkBoxesIdioma.add(cbOtroIdioma);
    }
    
    
    
    private void registarPersonal(){
        RegistroSelecciones registro = new RegistroSelecciones();
        String genero = seleccionGenero();
        String nacionalidad = seleccionNacionalidad();
        String civil = seleccionEstadoCivil();
        registro.registrarPersonales(genero, nacionalidad, civil);
    }
    
    
    
    public String seleccionGenero(){
        Enumeration<AbstractButton> btnGrp = buttonGroup1.getElements();
        String resultado = "";
        while(btnGrp.hasMoreElements())
        {
            JRadioButton btnAux = (JRadioButton)btnGrp.nextElement();
            if(btnAux.isSelected())
            {
                resultado = btnAux.getText();
            }
        }
        return resultado;
    }
    
    
    
    public String seleccionEstadoCivil(){
        Enumeration<AbstractButton> btnGrp = buttonGroup2.getElements();
        String resultado = "";
        while(btnGrp.hasMoreElements())
        {
            JRadioButton btnAux = (JRadioButton)btnGrp.nextElement();
            if(btnAux.isSelected())
            {
                resultado = btnAux.getText();
            }
        }
        return resultado;
    }
    
    
    public String seleccionNacionalidad(){
        Enumeration<AbstractButton> btnGrp = buttonGroup3.getElements();
        String resultado = "";
        while(btnGrp.hasMoreElements())
        {
            JRadioButton btnAux = (JRadioButton)btnGrp.nextElement();
            if(btnAux.isSelected()){
                resultado = btnAux.getText();
            }
        }
        return resultado;
    }


    
    private void registrarLenguajes(){
        RegistroSelecciones registro = new RegistroSelecciones();
        String otrosLenguajes = txtOtroLenguaje.getText();
        registro. registrarLenguajes(listaChkBoxesLenguaje, otrosLenguajes);
        }
    
    
    private void registrarIdiomas(){
        RegistroSelecciones registro = new RegistroSelecciones();
        registro. registrarIdiomas(listaChkBoxesIdioma);
    }

    
    
    /*Inicializando selecciones*/
    public void inicializarSelecciones(){
        /*Inicializando elementos*/
        rbMasculino.setSelected(true);
        rbSoltero.setSelected(true);
        rbMexicano.setSelected(true);
        txtOtroLenguaje.setVisible(false);
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        lblEncuesta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblGenero = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        lblEstadoCivil = new javax.swing.JLabel();
        rbSoltero = new javax.swing.JRadioButton();
        rbCasado = new javax.swing.JRadioButton();
        rbDivorciado = new javax.swing.JRadioButton();
        rbUnionLibre = new javax.swing.JRadioButton();
        lblNacionalidad = new javax.swing.JLabel();
        rbMexicano = new javax.swing.JRadioButton();
        rbExtranjero = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblLenguajesProgramacion = new javax.swing.JLabel();
        cbCPP = new javax.swing.JCheckBox();
        cbCS = new javax.swing.JCheckBox();
        cbJava = new javax.swing.JCheckBox();
        cbPHP = new javax.swing.JCheckBox();
        cbOtroLenguaje = new javax.swing.JCheckBox();
        cbIngles = new javax.swing.JCheckBox();
        cbFrances = new javax.swing.JCheckBox();
        cbAleman = new javax.swing.JCheckBox();
        cbOtroIdioma = new javax.swing.JCheckBox();
        lblIdiomas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOtroLenguaje = new javax.swing.JTextArea();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Radio Buttons y Check Boxes");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        lblEncuesta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEncuesta.setText("Encuesta");

        lblGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGenero.setText("Género");

        rbMasculino.setText("Masculino");

        rbFemenino.setText("Femenino");

        lblEstadoCivil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstadoCivil.setText("Estado Civil");

        rbSoltero.setText("Soltero");

        rbCasado.setText("Casado");

        rbDivorciado.setText("Divorciado");

        rbUnionLibre.setText("Union Libre");

        lblNacionalidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNacionalidad.setText("Nacionalidad");

        rbMexicano.setText("Mexicano");

        rbExtranjero.setText("Extranjero");
        rbExtranjero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExtranjeroActionPerformed(evt);
            }
        });

        lblLenguajesProgramacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLenguajesProgramacion.setText("Lenguajes Programacion");

        cbCPP.setText("C++");

        cbCS.setText("C#");

        cbJava.setText("Java");

        cbPHP.setText("PHP");

        cbOtroLenguaje.setText("Otro");
        cbOtroLenguaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbOtroLenguajeMouseClicked(evt);
            }
        });

        cbIngles.setText("Ingles");

        cbFrances.setText("Francés");

        cbAleman.setText("Aleman");

        cbOtroIdioma.setText("Otro");

        lblIdiomas.setText("Idiomas");

        txtOtroLenguaje.setColumns(20);
        txtOtroLenguaje.setRows(5);
        jScrollPane1.setViewportView(txtOtroLenguaje);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rbMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbFemenino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rbSoltero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbCasado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbDivorciado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbUnionLibre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPHP)
                                    .addComponent(cbJava))
                                .addGap(331, 331, 331)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbAleman)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbOtroIdioma)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblLenguajesProgramacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rbMexicano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(rbExtranjero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbOtroLenguaje)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbCS)
                                            .addComponent(cbCPP))
                                        .addGap(330, 330, 330)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbIngles)
                                            .addComponent(cbFrances)
                                            .addComponent(lblIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 98, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrar)
                                .addGap(17, 17, 17)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEncuesta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMasculino)
                    .addComponent(rbFemenino))
                .addGap(18, 18, 18)
                .addComponent(lblEstadoCivil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSoltero)
                    .addComponent(rbCasado)
                    .addComponent(rbDivorciado)
                    .addComponent(rbUnionLibre))
                .addGap(18, 18, 18)
                .addComponent(lblNacionalidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMexicano)
                    .addComponent(rbExtranjero))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLenguajesProgramacion)
                            .addComponent(lblIdiomas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCPP)
                            .addComponent(cbIngles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCS)
                            .addComponent(cbFrances))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbJava)
                            .addComponent(cbAleman))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPHP)
                            .addComponent(cbOtroIdioma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbOtroLenguaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegistrar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbExtranjeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExtranjeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbExtranjeroActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registarPersonal();
        registrarLenguajes();
        registrarIdiomas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cbOtroLenguajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbOtroLenguajeMouseClicked
        txtOtroLenguaje.setText(""); // limpiar cada que se da clic
        if(cbOtroLenguaje.isSelected())
            txtOtroLenguaje.setVisible(true);
        else
        txtOtroLenguaje.setVisible(false);
    }//GEN-LAST:event_cbOtroLenguajeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmButtons().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cbAleman;
    private javax.swing.JCheckBox cbCPP;
    private javax.swing.JCheckBox cbCS;
    private javax.swing.JCheckBox cbFrances;
    private javax.swing.JCheckBox cbIngles;
    private javax.swing.JCheckBox cbJava;
    private javax.swing.JCheckBox cbOtroIdioma;
    private javax.swing.JCheckBox cbOtroLenguaje;
    private javax.swing.JCheckBox cbPHP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEncuesta;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblIdiomas;
    private javax.swing.JLabel lblLenguajesProgramacion;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JRadioButton rbCasado;
    private javax.swing.JRadioButton rbDivorciado;
    private javax.swing.JRadioButton rbExtranjero;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbMexicano;
    private javax.swing.JRadioButton rbSoltero;
    private javax.swing.JRadioButton rbUnionLibre;
    private javax.swing.JTextArea txtOtroLenguaje;
    // End of variables declaration//GEN-END:variables
}
