/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.pvoe.sw.buttons.formas;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Enumeration;
import java.util.LinkedList;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import uam.pvoe.sw.buttons.modelo.AdministrarAlumno;
import uam.pvoe.sw.buttons.modelo.Alumno;
import uam.pvoe.sw.buttons.modelo.RegistroSelecciones;

/**
 *
 * @author compa
 */
public class FrmButtons extends javax.swing.JFrame {

    /**
     * Creates new form FrmButtons
     */
    /* Lista de CBXS para Actividades*/
    LinkedList<JCheckBox> listaChkBoxesActividades = new LinkedList();

    public FrmButtons() {
        initComponents();
        agruparCheckBoxesActividades();
        asignarRadioButtons();
        inicializarSelecciones();
    }

    public void agruparCheckBoxesActividades() {
        listaChkBoxesActividades.add(cbEncuestas);
        listaChkBoxesActividades.add(cbProceso);
        listaChkBoxesActividades.add(cbPERAJ);
    }

    public void asignarRadioButtons() {
        /*Genero*/
        bGroupGenero.add(rbMasculino);
        bGroupGenero.add(rbFemenino);
        bGroupGenero.add(rbNoBinario);
        /*Division*/
        bGroupDivision.add(rbCBI);
        bGroupDivision.add(rbCSH);
        bGroupDivision.add(rbCyAD);
    }

    /* Inicializar selecciones */
    public void inicializarSelecciones() {
        rbMasculino.setSelected(true);
        rbCBI.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroupGenero = new javax.swing.ButtonGroup();
        bGroupDivision = new javax.swing.ButtonGroup();
        lblSistema = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPrimerApellido = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        lblSegundoApellido = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        rbNoBinario = new javax.swing.JRadioButton();
        lblDivision = new javax.swing.JLabel();
        rbCBI = new javax.swing.JRadioButton();
        rbCSH = new javax.swing.JRadioButton();
        rbCyAD = new javax.swing.JRadioButton();
        lblActividades = new javax.swing.JLabel();
        cbEncuestas = new javax.swing.JCheckBox();
        cbProceso = new javax.swing.JCheckBox();
        cbPERAJ = new javax.swing.JCheckBox();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de actividades");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        lblSistema.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSistema.setText("Sistema de registro de actividades de cada estudiante");

        lblNombre.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblPrimerApellido.setText("Primer Apellido");

        lblSegundoApellido.setText("Segundo Apellido");

        lblMatricula.setText("Matrícula");

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });

        lblEdad.setText("Edad");

        lblGenero.setText("Género");

        rbMasculino.setText("Masculino");

        rbFemenino.setText("Femenino");

        rbNoBinario.setText("No binario");

        lblDivision.setText("División");

        rbCBI.setText("CBI");

        rbCSH.setText("CSH");

        rbCyAD.setText("CyAD");

        lblActividades.setText("Actividades que interesan");

        cbEncuestas.setText("Encuestas");
        cbEncuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEncuestasActionPerformed(evt);
            }
        });

        cbProceso.setText("Proceso de inscripción");
        cbProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProcesoActionPerformed(evt);
            }
        });

        cbPERAJ.setText("PERAJ");
        cbPERAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPERAJActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblSistema)
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtPrimerApellido)
                            .addComponent(txtSegundoApellido)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblPrimerApellido)
                                    .addComponent(lblSegundoApellido)
                                    .addComponent(lblMatricula)
                                    .addComponent(lblEdad)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnRegistrar)
                                        .addGap(7, 7, 7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(rbMasculino)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(rbFemenino))
                                                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(rbNoBinario))
                                            .addComponent(lblGenero)
                                            .addComponent(lblDivision)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbCBI)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbCSH)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbCyAD)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblActividades)
                                            .addComponent(cbEncuestas)
                                            .addComponent(cbProceso)
                                            .addComponent(cbPERAJ))))
                                .addGap(30, 30, 30)))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSistema)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrimerApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSegundoApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenero)
                    .addComponent(lblActividades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMasculino)
                    .addComponent(rbFemenino)
                    .addComponent(rbNoBinario)
                    .addComponent(cbEncuestas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDivision)
                    .addComponent(cbProceso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCBI)
                    .addComponent(rbCSH)
                    .addComponent(rbCyAD)
                    .addComponent(cbPERAJ))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void cbEncuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEncuestasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEncuestasActionPerformed

    private void cbPERAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPERAJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPERAJActionPerformed

    private void cbProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProcesoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        AdministrarAlumno administrar = new AdministrarAlumno();
        String nombre = txtNombre.getText();
        String primerApellido = txtPrimerApellido.getText();
        String segundoApellido = txtSegundoApellido.getText();
        String matricula = txtMatricula.getText();
        String edadTexto = txtEdad.getText();
        String genero = seleccionGenero();
        String division = seleccionDivision();

        StringBuilder actividadesStr = new StringBuilder();
        LinkedList<String> actividadesList = new LinkedList<>();
        for (JCheckBox chk : listaChkBoxesActividades) {
            if (chk.isSelected()) {
                actividadesList.add(chk.getText());
                if (actividadesStr.length() > 0) {
                    actividadesStr.append(", ");
                }
                actividadesStr.append(chk.getText());
            }
        }
        String actividades = actividadesStr.length() > 0 ? actividadesStr.toString() : "NINGUNA";

        if (nombre.isEmpty() || primerApellido.isEmpty() || segundoApellido.isEmpty()
                || matricula.isEmpty() || edadTexto.isEmpty() || genero.isEmpty() || division.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, llena todos los campos y selecciona género y división.",
                    "Campos vacíos",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int edad;
        try {
            edad = Integer.parseInt(edadTexto);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La edad debe ser un número válido.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (administrar.validarMatricula(matricula)) {
            Alumno alumno = new Alumno(nombre, primerApellido, segundoApellido, matricula, edad);
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Datos registrados:\n"
                    + "Nombre: " + alumno.getNombre() + "\n"
                    + "Primer Apellido: " + alumno.getPrimerApellido() + "\n"
                    + "Segundo Apellido: " + alumno.getSegundoApellido() + "\n"
                    + "Matrícula: " + alumno.getMatricula() + "\n"
                    + "Edad: " + alumno.getEdad() + "\n"
                    + "Género: " + genero + "\n"
                    + "División: " + division + "\n"
                    + "Actividades: " + actividades,
                    "Registro exitoso",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            guardarEnArchivo(alumno.getMatricula(), alumno.getPrimerApellido(),
                    alumno.getSegundoApellido(), alumno.getEdad(), genero,
                    division, actividadesList);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Matricula NO válida. Por favor verifica el dato.",
                    "Error de validación",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private String registrarAlumno() {
        RegistroSelecciones registro = new RegistroSelecciones();
        String genero = seleccionGenero();
        String division = seleccionDivision();
        return registro.registrarAlumnos(genero, division);
    }

    private String seleccionGenero() {
        Enumeration<AbstractButton> btnGrp = bGroupGenero.getElements();
        String resultado = "";
        while (btnGrp.hasMoreElements()) {
            JRadioButton btnAux = (JRadioButton) btnGrp.nextElement();
            if (btnAux.isSelected()) {
                resultado = btnAux.getText();
            }
        }
        return resultado;
    }

    private String seleccionDivision() {
        Enumeration<AbstractButton> btnGrp = bGroupDivision.getElements();
        String resultado = "";
        while (btnGrp.hasMoreElements()) {
            JRadioButton btnAux = (JRadioButton) btnGrp.nextElement();
            if (btnAux.isSelected()) {
                resultado = btnAux.getText();
            }
        }
        return resultado;
    }

    private String registrarActividades() {
        RegistroSelecciones registro = new RegistroSelecciones();
        return registro.registrarActividades(listaChkBoxesActividades);
    }

    public void guardarEnArchivo(String matricula, String primerApellido, String segundoApellido, int edad, String genero, String division, LinkedList<String> actividades) {
        String rutaArchivo = "src/alumnos.dat";
        StringBuilder sb = new StringBuilder();
        sb.append(matricula).append(",");
        sb.append(primerApellido).append(",");
        sb.append(segundoApellido).append(",");
        sb.append(edad).append(",");
        sb.append(genero).append(",");
        sb.append(division);

        if (actividades.isEmpty()) {
            sb.append(",NINGUNA");
        } else {
            for (String act : actividades) {
                sb.append(",").append(act);
            }
        }
        sb.append("\n");

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(rutaArchivo, true))) {
            writer.write(sb.toString());
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error al guardar en archivo: " + e.getMessage());
        }
    }

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmButtons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmButtons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGroupDivision;
    private javax.swing.ButtonGroup bGroupGenero;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox cbEncuestas;
    private javax.swing.JCheckBox cbPERAJ;
    private javax.swing.JCheckBox cbProceso;
    private javax.swing.JLabel lblActividades;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrimerApellido;
    private javax.swing.JLabel lblSegundoApellido;
    private javax.swing.JLabel lblSistema;
    private javax.swing.JRadioButton rbCBI;
    private javax.swing.JRadioButton rbCSH;
    private javax.swing.JRadioButton rbCyAD;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbNoBinario;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtSegundoApellido;
    // End of variables declaration//GEN-END:variables
}
