/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.pvoe.sw.ei.formas;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import uam.pvoe.sw.ei.operaciones.GestionInfantes;

/**
 *
 * @author btosk
 */
public class ConsultaNivelesFrm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaNivelesFrm.class.getName());

    /**
     * Creates new form ConsultaNivelesFrm
     */
    public ConsultaNivelesFrm() {
        initComponents();
        cargarDatos();
    }

    
    private void cargarDatos() {
        GestionInfantes operaciones = new GestionInfantes();
    
        // modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        operaciones.llenarTablaInicial(modelo);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblFiltro = new javax.swing.JLabel();
        cmbFiltroNivel = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBaja = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnActualizarCuota = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estancia Infantil - Azcapotzalco: Consulta de Niveles");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setText("Consulta por Niveles");

        lblFiltro.setText("Filtrar por Nivel");

        cmbFiltroNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lactantes (45 dias a 11 meses)", "Maternal (1 a 2 años)", "Preescolar (3 a 4 años)" }));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Nivel", "Deuda/Costo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnBaja.setText("Dar de Baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar al Menu");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnActualizarCuota.setText("Actualizar cuota");
        btnActualizarCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCuotaActionPerformed(evt);
            }
        });

        btnEditar.setText("Actualizar Datos");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbFiltroNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnBuscar))
                            .addComponent(lblFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizarCuota)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(40, 40, 40))
                    .addComponent(lblFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFiltroNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnRegresar)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBaja)
                            .addComponent(btnEditar)
                            .addComponent(btnActualizarCuota))
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        MenuPrincipalFrm menu = new MenuPrincipalFrm();
        menu.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed

        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            return;
        }

        String nombre = jTable1.getValueAt(fila, 0).toString(); // Obtenener nombre para el log

        String razon = JOptionPane.showInputDialog(this, "Ingrese razón de baja:");

        if (razon != null) {
            
            GestionInfantes operaciones = new GestionInfantes();

            if(operaciones.procesarBaja(nombre, razon)) {
                // actualizar tabla SOLO VISUAL hasta que se pongan los txt
                ((javax.swing.table.DefaultTableModel)jTable1.getModel()).removeRow(fila);
                javax.swing.JOptionPane.showMessageDialog(this, "Baja procesada correctamente.");
            }
        }
    }//GEN-LAST:event_btnBajaActionPerformed

    
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Simulación de búsqueda
        String nivel = (String) cmbFiltroNivel.getSelectedItem();
        JOptionPane.showMessageDialog(this, "Filtrando alumnos por nivel: " + nivel);
        // Aquí en el futuro se recargaría la tabla (JTable) ya con lo de los txt
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    
    private void btnActualizarCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCuotaActionPerformed
        int fila = jTable1.getSelectedRow();
    
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un infante.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener datos de la vista
        String nivelActual = jTable1.getValueAt(fila, 2).toString();

        
        
        int resp = JOptionPane.showConfirmDialog(this, "¿Requiere dieta especial?", "Actualizar", JOptionPane.YES_NO_OPTION);
        boolean quiereDieta = (resp == JOptionPane.YES_OPTION);

        
        
        GestionInfantes operaciones = new GestionInfantes();
        double nuevoTotal = operaciones.calcularNuevaCuota(nivelActual, quiereDieta);

        
        
        // Actualizar la vista
        jTable1.setValueAt("$" + nuevoTotal, fila, 3);
        javax.swing.JOptionPane.showMessageDialog(this, "Cuota actualizada.");
    }//GEN-LAST:event_btnActualizarCuotaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // 1. Verificar si seleccionó una fila
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un infante para editar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Obtener los valores actuales de la tabla
        // Columna 0: Nombre, Columna 1: Apellidos
        String nombreActual = jTable1.getValueAt(fila, 0).toString();
        String apellidosActual = jTable1.getValueAt(fila, 1).toString();

        // 3. Pedir nuevos datos usando InputDialogs
        String nuevoNombre = javax.swing.JOptionPane.showInputDialog(this, "Editar Nombre:", nombreActual);

        // Si el usuario cancela, nuevoNombre será null, así que validamos
        if (nuevoNombre == null) return; 

        String nuevosApellidos = javax.swing.JOptionPane.showInputDialog(this, "Editar Apellidos:", apellidosActual);
        if (nuevosApellidos == null) return;

        // 4. Guardar los cambios en la tabla (Visualmente)
        jTable1.setValueAt(nuevoNombre, fila, 0);
        jTable1.setValueAt(nuevosApellidos, fila, 1);

        javax.swing.JOptionPane.showMessageDialog(this, "Datos actualizados correctamente.");

        // NOTA PARA EL FUTURO:
        // Aquí deberías llamar a tu clase de Operaciones para actualizar el archivo TXT real.
        // Ej: operaciones.actualizarInfante(fila, nuevoNombre, nuevosApellidos);
    }//GEN-LAST:event_btnEditarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaNivelesFrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCuota;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbFiltroNivel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

}
